#!/usr/bin/env perl

use strict;
use warnings;

my $commit_msg_file = $ARGV[0];
print $ARGV[1];
my $commit_msg = do{local(@ARGV,$/)=$commit_msg_file;<>};
print "Writing to $commit_msg_file\n";
open(my $fh, '>', $commit_msg_file);
print $fh $commit_msg;
close $fh;
