#!/usr/bin/env perl

use strict;
use warnings;

my $commit_msg_file = $ARGV[0];
my $commit_msg = do{local(@ARGV,$/)=$commit_msg_file;<>};
open(my $fh, '>', $commit_msg_file);
print $fh "[skip ci] $commit_msg";
close $fh;
